name: Update README
on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes.
jobs:
  build:
    runs-on: windows
    name: Update this repo's README with recent activity
    steps:
      - uses: actions/checkout@v2
      - uses: actions-js/profile-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: vasantisuthar
          COMMIT_MSG: "Updated README with recent activity"
          
